In [ ]:
# COMPUTSTAT Financial Formulas   https://sites.bu.edu/qm222projectcourse/files/2014/08/compustat_users_guide-2003.pdf

In [4]:
import pandas as pd
import numpy as np

# Define the path to the CSV file
csv_path = "C:\\ASAM_Local\\WRDS.COMPUSTAT.NA.ALL.9.27.23.csv"

# Read the CSV file into a DataFrame
compustat = pd.read_csv(csv_path, parse_dates=['datadate'], dtype={"gvkey": np.int64}, low_memory=False)

# Print available columns for debugging
print("Available columns:")
print(compustat.columns)

# Filter based on conditions and select columns in a single step
try:
    compustat = compustat.loc[
        (compustat['datadate'] >= '1963-01-01') & 
        (compustat['datadate'] <= '2022-12-31') & 
        (compustat['datafmt'] == 'STD') & 
        (compustat['consol'] == 'C'),
        ['gvkey', 'cusip', 'conm', 'tic', 'gsector', 'ggroup', 'gind', 'datadate', 'fyear', 'fyr', 'ni', 'seq', 'ceq',
         'at', 'lt', 'txditc', 'txdb', 'itcb', 'pstkrv', 'pstkl', 'pstk', 'capx', 'oancf', 'sale', 'cogs', 'xint', 'xsga']
    ]
except KeyError as e:
    print(f"KeyError: {e}")

print(compustat.head())

### Industrial Format (INDL): This specifies that you want the data in an industrial format.
### FS - Financial Services (includes banks, insurance companies, broker/dealers, real estate and other financial services)
###INDL - Industrial (includes companies reporting manufacturing, retail, construction and other commercial operations other than financial services)

# Usually, financial databases contain data in multiple formats for different types of analyses.
# By specifying INDL, you're choosing a format that is standardized for industrial companies,
# which makes it easier to compare firms across the same industry or various industries.

# datafmt = 'STD'
# Standard Data Format (STD): Databases like Compustat often provide data in various formatsâ€”standardized (STD),
# as-reported, etc. Choosing the standard format ensures that the data is presented in a consistent manner,
# irrespective of how individual companies report their data. 
# This is crucial for conducting analyses where comparability across companies is essential.

# consol = 'C'
# Consolidated (C): This specifies that you're interested in consolidated financial statements, 
# which include all subsidiaries and business operations. This is in contrast to standalone or parent-only financial statements.
# Using consolidated statements gives a fuller picture of a company's financial health and performance,
# especially if it has multiple divisions or subsidiaries.

# gvkey: Global Company Key - A unique identifier for each company.
# datadate: Date of Data - The date the financial data was reported.
# ni: net income represents the income or loss reported by a company after expenses and losses have been subtracted from all revenues and gains for the fiscal period including extraordinary items and discontinued operations.
# seq: Stockholder's Equity - The value of the ownership interest in the firm, calculated as Assets - Liabilities.
# ceq: Common Equity - The value of just the common equity portion of the stockholder's equity, not including preferred shares.
# at: Total Assets - The total economic resources the firm controls.
# lt: Total Liabilities - All the obligations or debts a company has to pay.
# txditc: Deferred Taxes & Investment Tax Credit - Deferred income tax assets/liabilities and investment tax credits,
#         which may be used to reduce future taxable income.
# txdb: Deferred Taxes - The balance of deferred tax assets or liabilities.
# itcb: Investment Tax Credit - Reductions in tax liability as an incentive for making specific investments.
# pstkrv: Preferred Stock Redemption Value - The value at which preferred stock will be redeemed.
# pstkl: Preferred Stock Liquidation Value - The value each preferred share will receive if the company is liquidated.
# pstk: Preferred Stock Carrying Value - The value of preferred stock at its carrying value on the balance sheet.
# capx: Capital Expenditures - Investments in property, plant, equipment, or other long-term assets.
# oancf: Operating Activities Net Cash Flow - Cash generated from core operating business activities.
# sale: Sales or Revenue - Total amount of sales made or revenue generated.
# cogs: Cost of Goods Sold - Direct costs attributable to the production of the goods sold by a company.
# xint: Interest Expense - The cost of debt that has occurred during a specified period.
# xsga: Selling, General and Administrative Expenses - Combined total of all indirect costs associated with running a business.

Available columns:
Index(['gvkey', 'datadate', 'fyear', 'indfmt', 'consol', 'popsrc', 'datafmt',
       'tic', 'cusip', 'conm',
       ...
       'priusa', 'sic', 'spcindcd', 'spcseccd', 'spcsrc', 'state', 'stko',
       'weburl', 'dldte', 'ipodate'],
      dtype='object', length=1858)
   gvkey      cusip                   conm   tic  gsector  ggroup  gind  \
2   1000  000032102  A & E PLASTIK PAK INC  AE.2      NaN     NaN   NaN
3   1000  000032102  A & E PLASTIK PAK INC  AE.2      NaN     NaN   NaN
4   1000  000032102  A & E PLASTIK PAK INC  AE.2      NaN     NaN   NaN
5   1000  000032102  A & E PLASTIK PAK INC  AE.2      NaN     NaN   NaN
6   1000  000032102  A & E PLASTIK PAK INC  AE.2      NaN     NaN   NaN

    datadate  fyear  fyr  ...  itcb  pstkrv  pstkl  pstk   capx  oancf   sale  \
2 1963-12-31   1963   12  ...   0.0     0.0    0.0   0.0    NaN    NaN  1.457
3 1964-12-31   1964   12  ...   0.0     0.0    0.0   0.0    NaN    NaN  2.032
4 1965-12-31   1965   12  ...   0.0     0.0    0.0   0.0    NaN    NaN  1.688
5 1966-12-31   1966   12  ...   0.0     0.0    0.0   0.0  0.118    NaN  4.032
6 1967-12-31   1967   12  ...   0.0     0.0    0.0   0.0  0.180    NaN  3.594

    cogs   xint   xsga
2  1.065  0.020  0.346
3  1.474  0.033  0.431
4  1.342  0.062  0.506
5  2.828  0.095  0.679
6  2.701  0.097  0.692

[5 rows x 27 columns]

In [7]:
compustat.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 523179 entries, 2 to 538936
Data columns (total 27 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   gvkey     523179 non-null  int64
 1   cusip     523086 non-null  object
 2   conm      523179 non-null  object
 3   tic       523083 non-null  object
 4   gsector   443392 non-null  float64
 5   ggroup    443392 non-null  float64
 6   gind      443392 non-null  float64
 7   datadate  523179 non-null  datetime64[ns]
 8   fyear     523179 non-null  int64
 9   fyr       523179 non-null  int64
 10  ni        406971 non-null  float64
 11  seq       442670 non-null  float64
 12  ceq       444076 non-null  float64
 13  at        448598 non-null  float64
 14  lt        446506 non-null  float64
 15  txditc    371635 non-null  float64
 16  txdb      403622 non-null  float64
 17  itcb      371866 non-null  float64
 18  pstkrv    405838 non-null  float64
 19  pstkl     407389 non-null  float64
 20  pstk      448617 non-null  float64
 21  capx      379356 non-null  float64
 22  oancf     267830 non-null  float64
 23  sale      407955 non-null  float64
 24  cogs      406140 non-null  float64
 25  xint      400353 non-null  float64
 26  xsga      331790 non-null  float64
dtypes: datetime64[ns](1), float64(20), int64(3), object(3)
memory usage: 111.8+ MB

In [8]:
# First, calculate the initial 'be' (Book Equity) column
compustat = compustat.assign(
    # Create a new column 'be' for Book Equity
    be = lambda x: (
        # Try using 'seq' (Stockholder's Equity) if available
        x["seq"].combine_first(
            # If 'seq' is not available, fallback to the sum of 'ceq' (Common Equity) and 'pstk' (Preferred Stock)
            x["ceq"] + x["pstk"]
        )
        # If both 'seq' and the sum of 'ceq' and 'pstk' are not available, use 'at' (Total Assets) minus 'lt' (Total Liabilities)
        .combine_first(x["at"] - x["lt"])
        
        # Add 'txditc' (Deferred Taxes & Investment Tax Credit), if not available, fallback to the sum of 'txdb' and 'itcb'
        + x["txditc"].combine_first(x["txdb"] + x["itcb"]).fillna(0)
        
        # Subtract any values in 'pstkrv' (Preferred Stock Redemption Value), if not available, fallback to 'pstkl' or 'pstk'
        - x["pstkrv"].combine_first(x["pstkl"]).combine_first(x["pstk"]).fillna(0)
    )
)

# Next, update the 'be' column to replace negative or zero values with NaN (Not a Number)
# This is a common practice when dealing with book-to-market ratios
compustat["be"] = compustat["be"].apply(
    lambda y: np.nan if y <= 0 else y
)

# Lastly, calculate 'op' (Operating Profitability)
compustat = compustat.assign(
    # Create a new column 'op' for Operating Profitability
    op = lambda x: (
        # Calculate Operating Income: 'sale' (Sales) - 'cogs' (Cost of Goods Sold) - 'xsga' (Selling, General & Admin Expenses) - 'xint' (Interest Expenses)
        (x["sale"] - x["cogs"].fillna(0) - x["xsga"].fillna(0) - x["xint"].fillna(0))
        
        # Divide the Operating Income by the Book Value of Equity ('be') to get Operating Profitability
        / x["be"]
    )
)

compustat.tail(12)

,gvkey,cusip,conm,tic,gsector,ggroup,gind,datadate,fyear,fyr,...,pstkl,pstk,capx,oancf,sale,cogs,xint,xsga,be,op
538925,351491,N47017103,IVECO GROUP N V,IVCGF,20.0,2010.0,201060.0,2020-12-31,2020,12,...,0.000,0.000,483.000,674.000,12549.000,10413.000,117.000,1078.000,2747.000,0.342556
538926,351491,N47017103,IVECO GROUP N V,IVCGF,20.0,2010.0,201060.0,2021-12-31,2021,12,...,0.000,0.000,641.452,613.019,14388.308,11738.339,112.595,1227.175,2615.850,0.500869
538927,351491,N47017103,IVECO GROUP N V,IVCGF,20.0,2010.0,201060.0,2022-12-31,2022,12,...,1.069,1.069,830.413,1503.721,15343.932,12607.952,203.061,1261.116,2541.469,0.500420
538928,351590,23384L101,DAIMLER TRUCK HOLDING AG,DTRUY,20.0,2010.0,201060.0,2019-12-31,2019,12,...,0.000,0.000,1268.066,1425.172,51894.216,39804.942,228.925,7095.561,11161.229,0.426905
538929,351590,23384L101,DAIMLER TRUCK HOLDING AG,DTRUY,20.0,2010.0,201060.0,2020-12-31,2020,12,...,0.000,0.000,959.487,5026.460,43409.566,34088.316,171.165,6522.343,10033.633,0.261893
538930,351590,23384L101,DAIMLER TRUCK HOLDING AG,DTRUY,20.0,2010.0,201060.0,2021-12-31,2021,12,...,0.000,0.000,866.642,2388.384,45224.620,34907.939,122.831,6405.419,18183.563,0.208344
538931,351590,23384L101,DAIMLER TRUCK HOLDING AG,DTRUY,20.0,2010.0,201060.0,2022-12-31,2022,12,...,0.000,0.000,959.731,-558.952,54322.030,41874.390,203.061,6753.383,21499.887,0.255406
538932,352262,G2415A113,COOL COMPANY LTD,CLCO,10.0,1010.0,101020.0,2022-12-31,2022,12,...,0.000,0.000,353.506,118.234,212.978,42.103,22.072,14.004,646.557,0.208487
538933,353444,405552100,HALEON PLC,HLN,30.0,3030.0,303020.0,2021-12-31,2021,12,...,0.000,0.000,308.735,1836.160,12924.885,4445.511,21.665,5299.946,40233.020,0.078487
538934,353444,405552100,HALEON PLC,HLN,30.0,3030.0,303020.0,2022-12-31,2022,12,...,0.000,0.000,366.290,2485.709,13082.804,4629.226,306.044,5194.324,24016.067,0.122968
538935,353945,00449R109,ACCELLERON INDUSTRIES AG,ACLLY,20.0,2010.0,201040.0,2021-12-31,2021,12,...,0.000,0.000,28.855,163.283,756.466,377.304,1.379,172.669,305.149,0.672177
538936,353945,00449R109,ACCELLERON INDUSTRIES AG,ACLLY,20.0,2010.0,201040.0,2022-12-31,2022,12,...,0.000,0.000,34.425,133.388,780.538,404.969,0.555,200.689,316.595,0.550625

In [9]:
# Calculate the lagged assets for each firm for each year
compustat_lag = (compustat
  .get(["gvkey", "fyear", "at"])
  .assign(year=lambda x: x["fyear"] + 1)
  .rename(columns={"at": "at_lag"})
)

# Merge the lagged assets back to the original dataframe and calculate the investment ratio
compustat = (compustat
  .merge(compustat_lag, how="left", on=["gvkey", "fyear"])
  .assign(
    inv = lambda x: x["at"] / x["at_lag"] - 1  # Calculate investment ratio
  )
  .assign(
    inv = lambda x: 
      np.where(x["at_lag"] <= 0, np.nan, x["inv"])  # Handle division by zero
  )
)

# Show the tail of the updated dataframe
compustat.tail(12)

,gvkey,cusip,conm,tic,gsector,ggroup,gind,datadate,fyear,fyr,...,oancf,sale,cogs,xint,xsga,be,op,at_lag,year,inv
609845,351491,N47017103,IVECO GROUP N V,IVCGF,20.0,2010.0,201060.0,2020-12-31,2020,12,...,674.000,12549.000,10413.000,117.000,1078.000,2747.000,0.342556,18841.000,2021,0.0
609846,351491,N47017103,IVECO GROUP N V,IVCGF,20.0,2010.0,201060.0,2021-12-31,2021,12,...,613.019,14388.308,11738.339,112.595,1227.175,2615.850,0.500869,18834.114,2022,0.0
609847,351491,N47017103,IVECO GROUP N V,IVCGF,20.0,2010.0,201060.0,2022-12-31,2022,12,...,1503.721,15343.932,12607.952,203.061,1261.116,2541.469,0.500420,17113.769,2023,0.0
609848,351590,23384L101,DAIMLER TRUCK HOLDING AG,DTRUY,20.0,2010.0,201060.0,2019-12-31,2019,12,...,1425.172,51894.216,39804.942,228.925,7095.561,11161.229,0.426905,62131.888,2020,0.0
609849,351590,23384L101,DAIMLER TRUCK HOLDING AG,DTRUY,20.0,2010.0,201060.0,2020-12-31,2020,12,...,5026.460,43409.566,34088.316,171.165,6522.343,10033.633,0.261893,60256.041,2021,0.0
609850,351590,23384L101,DAIMLER TRUCK HOLDING AG,DTRUY,20.0,2010.0,201060.0,2021-12-31,2021,12,...,2388.384,45224.620,34907.939,122.831,6405.419,18183.563,0.208344,62325.449,2022,0.0
609851,351590,23384L101,DAIMLER TRUCK HOLDING AG,DTRUY,20.0,2010.0,201060.0,2022-12-31,2022,12,...,-558.952,54322.030,41874.390,203.061,6753.383,21499.887,0.255406,68366.372,2023,0.0
609852,352262,G2415A113,COOL COMPANY LTD,CLCO,10.0,1010.0,101020.0,2022-12-31,2022,12,...,118.234,212.978,42.103,22.072,14.004,646.557,0.208487,2058.061,2023,0.0
609853,353444,405552100,HALEON PLC,HLN,30.0,3030.0,303020.0,2021-12-31,2021,12,...,1836.160,12924.885,4445.511,21.665,5299.946,40233.020,0.078487,46650.099,2022,0.0
609854,353444,405552100,HALEON PLC,HLN,30.0,3030.0,303020.0,2022-12-31,2022,12,...,2485.709,13082.804,4629.226,306.044,5194.324,24016.067,0.122968,41948.594,2023,0.0
609855,353945,00449R109,ACCELLERON INDUSTRIES AG,ACLLY,20.0,2010.0,201040.0,2021-12-31,2021,12,...,163.283,756.466,377.304,1.379,172.669,305.149,0.672177,686.085,2022,0.0
609856,353945,00449R109,ACCELLERON INDUSTRIES AG,ACLLY,20.0,2010.0,201040.0,2022-12-31,2022,12,...,133.388,780.538,404.969,0.555,200.689,316.595,0.550625,981.551,2023,0.0

In [10]:
from pandas.tseries.offsets import DateOffset

# Add a new column and name it 'datadate_3ML'
compustat['datadate_3ML'] = compustat['datadate'] + DateOffset(months=3)

# Show the first few rows to confirm that the new column has been added correctly
print(compustat[['datadate', 'datadate_3ML']].tail())

         datadate datadate_3ML
609852 2022-12-31   2023-03-31
609853 2021-12-31   2022-03-31
609854 2022-12-31   2023-03-31
609855 2021-12-31   2022-03-31
609856 2022-12-31   2023-03-31

In [11]:
compustat1 = compustat[['gvkey', 'cusip', 'conm', 'tic', 'gsector', 'ggroup', 'gind', 'datadate', 
                        'datadate_3ML',  'fyear', 'year', 'fyr', 'ni', 'seq', 'ceq', 'at', 'at_lag', 'lt', 'txditc', 
                        'txdb', 'itcb', 'pstkrv', 'pstkl', 'pstk', 'capx', 'oancf', 'sale', 'cogs', 
                        'xint', 'xsga', 'be', 'op', 'inv']].copy()

compustat1.tail()

,gvkey,cusip,conm,tic,gsector,ggroup,gind,datadate,datadate_3ML,fyear,...,oancf,sale,cogs,xint,xsga,be,op,at_lag,year,inv
609852,352262,G2415A113,COOL COMPANY LTD,CLCO,10.0,1010.0,101020.0,2022-12-31,2023-03-31,2022,...,118.234,212.978,42.103,22.072,14.004,646.557,0.208487,2058.061,2023,0.0
609853,353444,405552100,HALEON PLC,HLN,30.0,3030.0,303020.0,2021-12-31,2022-03-31,2021,...,1836.160,12924.885,4445.511,21.665,5299.946,40233.020,0.078487,46650.099,2022,0.0
609854,353444,405552100,HALEON PLC,HLN,30.0,3030.0,303020.0,2022-12-31,2023-03-31,2022,...,2485.709,13082.804,4629.226,306.044,5194.324,24016.067,0.122968,41948.594,2023,0.0
609855,353945,00449R109,ACCELLERON INDUSTRIES AG,ACLLY,20.0,2010.0,201040.0,2021-12-31,2022-03-31,2021,...,163.283,756.466,377.304,1.379,172.669,305.149,0.672177,686.085,2022,0.0
609856,353945,00449R109,ACCELLERON INDUSTRIES AG,ACLLY,20.0,2010.0,201040.0,2022-12-31,2023-03-31,2022,...,133.388,780.538,404.969,0.555,200.689,316.595,0.550625,981.551,2023,0.0

In [14]:
# Create a copy if your dataframe is a slice
compustat1 = compustat1.copy()

# Convert to numeric types
compustat1['gsector'] = pd.to_numeric(compustat1['gsector'], errors='coerce')
compustat1['ggroup'] = pd.to_numeric(compustat1['ggroup'], errors='coerce')

# Function to transform GICS sector codes to sector names
def assign_gsector(sector):
    mapping = {
        10: "Energy",
        15: "Materials",
        20: "Industrials",
        25: "Consumer Discretionary",
        30: "Consumer Staples",
        35: "Health Care",
        40: "Financials",
        45: "Information Technology",
        50: "Communication Services",
        55: "Utilities",
        60: "Real Estate"
    }
    return mapping.get(sector, "Missing")

# Function to transform GICS group codes to group names
def assign_ggroup(group):
    mapping = {
        1010: "Energy",
        1510: "Materials",
        2010: "Capital Goods",
        2020: "Commercial & Professional Services",
        2030: "Transportation",
        2510: "Automobiles & Components",
        2520: "Consumer Durables & Apparel",
        2530: "Consumer Services",
        2540: "Media & Entertainment",
        2550: "Retailing",
        3010: "Food & Staples Retailing",
        3020: "Food, Beverage & Tobacco",
        3030: "Household & Personal Products",
        3510: "Health Care Equipment & Services",
        3520: "Pharmaceuticals, Biotechnology & Life Sciences",
        4010: "Banks",
        4020: "Diversified Financials",
        4030: "Insurance",
        4040: "Real Estate",
        4510: "Software & Services",
        4520: "Technology Hardware & Equipment",
        4530: "Semiconductors & Semiconductor Equipment",
        5010: "Telecommunication Services",
        5020: "Media & Entertainment",
        5510: "Utilities",
        6010: "Real Estate"
    }
    return mapping.get(group, "Missing")

# Add the 'gsector_name' and 'ggroup_name' columns
compustat1.loc[:, 'gsector_name'] = compustat1["gsector"].apply(assign_gsector)
compustat1.loc[:, 'ggroup_name'] = compustat1["ggroup"].apply(assign_ggroup)

In [17]:
compustat1 = compustat1[['gvkey', 'cusip', 'conm', 'tic', 'gsector_name', 'ggroup_name', 'datadate', 
                        'datadate_3ML',  'fyear', 'fyr', 'ni', 'seq', 'ceq', 'at', 'at_lag', 'lt', 'txditc', 
                        'txdb', 'itcb', 'pstkrv', 'pstkl', 'pstk', 'capx', 'oancf', 'sale', 'cogs', 
                        'xint', 'xsga', 'be', 'op', 'inv']].copy()

compustat1.tail()

,gvkey,cusip,conm,tic,gsector_name,ggroup_name,datadate,datadate_3ML,fyear,fyr,...,pstk,capx,oancf,sale,cogs,xint,xsga,be,op,inv
609852,352262,G2415A113,COOL COMPANY LTD,CLCO,Energy,Energy,2022-12-31,2023-03-31,2022,12,...,0.0,353.506,118.234,212.978,42.103,22.072,14.004,646.557,0.208487,0.0
609853,353444,405552100,HALEON PLC,HLN,Consumer Staples,Household & Personal Products,2021-12-31,2022-03-31,2021,12,...,0.0,308.735,1836.160,12924.885,4445.511,21.665,5299.946,40233.020,0.078487,0.0
609854,353444,405552100,HALEON PLC,HLN,Consumer Staples,Household & Personal Products,2022-12-31,2023-03-31,2022,12,...,0.0,366.290,2485.709,13082.804,4629.226,306.044,5194.324,24016.067,0.122968,0.0
609855,353945,00449R109,ACCELLERON INDUSTRIES AG,ACLLY,Industrials,Capital Goods,2021-12-31,2022-03-31,2021,12,...,0.0,28.855,163.283,756.466,377.304,1.379,172.669,305.149,0.672177,0.0
609856,353945,00449R109,ACCELLERON INDUSTRIES AG,ACLLY,Industrials,Capital Goods,2022-12-31,2023-03-31,2022,12,...,0.0,34.425,133.388,780.538,404.969,0.555,200.689,316.595,0.550625,0.0

In [18]:
# Convert 'fyr' in compustat1 to numeric type
compustat1['fyr'] = pd.to_numeric(compustat1['fyr'], errors='coerce')

# Function to transform 'fyr' code to month names
def assign_fyr_month(fyr_code):
    month_mapping = {
        1: "January",
        2: "February",
        3: "March",
        4: "April",
        5: "May",
        6: "June",
        7: "July",
        8: "August",
        9: "September",
        10: "October",
        11: "November",
        12: "December"
    }
    return month_mapping.get(fyr_code, "Missing")

# Add the 'fyr_month' column to compustat1
compustat1.loc[:, 'fyr_month'] = compustat1["fyr"].apply(assign_fyr_month)

# Assuming mcrsp is your original DataFrame
compustat1 = compustat1[['gvkey', 'cusip', 'conm', 'tic', 'gsector_name', 'ggroup_name', 'datadate', 
                        'datadate_3ML',  'fyr_month', 'fyear', 'ni', 'seq', 'ceq', 'at', 'at_lag', 'lt', 'txditc', 
                        'txdb', 'itcb', 'pstkrv', 'pstkl', 'pstk', 'capx', 'oancf', 'sale', 'cogs', 
                        'xint', 'xsga', 'be', 'op', 'inv']].copy()

compustat1.tail()

,gvkey,cusip,conm,tic,gsector_name,ggroup_name,datadate,datadate_3ML,fyr_month,fyear,...,pstk,capx,oancf,sale,cogs,xint,xsga,be,op,inv
609852,352262,G2415A113,COOL COMPANY LTD,CLCO,Energy,Energy,2022-12-31,2023-03-31,December,2022,...,0.0,353.506,118.234,212.978,42.103,22.072,14.004,646.557,0.208487,0.0
609853,353444,405552100,HALEON PLC,HLN,Consumer Staples,Household & Personal Products,2021-12-31,2022-03-31,December,2021,...,0.0,308.735,1836.160,12924.885,4445.511,21.665,5299.946,40233.020,0.078487,0.0
609854,353444,405552100,HALEON PLC,HLN,Consumer Staples,Household & Personal Products,2022-12-31,2023-03-31,December,2022,...,0.0,366.290,2485.709,13082.804,4629.226,306.044,5194.324,24016.067,0.122968,0.0
609855,353945,00449R109,ACCELLERON INDUSTRIES AG,ACLLY,Industrials,Capital Goods,2021-12-31,2022-03-31,December,2021,...,0.0,28.855,163.283,756.466,377.304,1.379,172.669,305.149,0.672177,0.0
609856,353945,00449R109,ACCELLERON INDUSTRIES AG,ACLLY,Industrials,Capital Goods,2022-12-31,2023-03-31,December,2022,...,0.0,34.425,133.388,780.538,404.969,0.555,200.689,316.595,0.550625,0.0

In [24]:
# Rename cusip to CUSIP and datadate to monthend to merge with COMPUSTAT
compustat1.rename(columns={'cusip': 'CUSIP'}, inplace=True)
compustat1.rename(columns={'datadate': 'monthend'}, inplace=True)
compustat1.rename(columns={'conm': 'CONNAM'}, inplace=True)
compustat1.rename(columns={'tic': 'TICKER'}, inplace=True)

compustat1.tail()

,gvkey,CUSIP,CONNAM,TICKER,gsector_name,ggroup_name,monthend,datadate_3ML,fyr_month,fyear,...,pstk,capx,oancf,sale,cogs,xint,xsga,be,op,inv
609852,352262,G2415A113,COOL COMPANY LTD,CLCO,Energy,Energy,2022-12-31,2023-03-31,December,2022,...,0.0,353.506,118.234,212.978,42.103,22.072,14.004,646.557,0.208487,0.0
609853,353444,405552100,HALEON PLC,HLN,Consumer Staples,Household & Personal Products,2021-12-31,2022-03-31,December,2021,...,0.0,308.735,1836.160,12924.885,4445.511,21.665,5299.946,40233.020,0.078487,0.0
609854,353444,405552100,HALEON PLC,HLN,Consumer Staples,Household & Personal Products,2022-12-31,2023-03-31,December,2022,...,0.0,366.290,2485.709,13082.804,4629.226,306.044,5194.324,24016.067,0.122968,0.0
609855,353945,00449R109,ACCELLERON INDUSTRIES AG,ACLLY,Industrials,Capital Goods,2021-12-31,2022-03-31,December,2021,...,0.0,28.855,163.283,756.466,377.304,1.379,172.669,305.149,0.672177,0.0
609856,353945,00449R109,ACCELLERON INDUSTRIES AG,ACLLY,Industrials,Capital Goods,2022-12-31,2023-03-31,December,2022,...,0.0,34.425,133.388,780.538,404.969,0.555,200.689,316.595,0.550625,0.0

In [25]:
compustat1.to_csv('C:/ASAM_Local/WRDS.COMPUSTAT.ASTOCK.1963_2022.V1.csv', index=False)